export const COLOR_LIST = [

    { color : 'Black'},
    { color : '#202020'},
    { color : '#2b2b2b'},
    { color : 'DarkGrey'},


    { color : 'White'},
    { color : 'WhiteSmoke'},


    { color : 'Aqua'},
    { color : 'Aquamarine'},
    { color : 'Bisque'},

    { color : 'DarkBlue'},
    { color : 'Blue'},
    { color : 'CornflowerBlue'},
    { color : 'CadetBlue'},
    { color : 'BlueViolet'},
    { color : 'DarkSlateBlue'},
    { color : 'DeepSkyBlue'},
    { color : 'DodgerBlue'},
    { color : 'MediumSlateBlue'},
    { color : 'LightSkyBlue'},
    { color : 'LightSteelBlue'},
    { color : 'MidnightBlue'},

    { color : 'Brown'},
    { color : 'BurlyWood'},

    { color : 'Chartreuse'},
    { color : 'Chocolate'},
    { color : 'Coral'},

    { color : 'Crimson'},
    { color : 'Cyan'},

    { color : 'DarkCyan'},
    { color : 'DarkGoldenRod'},
    { color : 'DarkGreen'},
    { color : 'DarkKhaki'},
    { color : 'DarkMagenta'},
    { color : 'DarkOliveGreen'},
    { color : 'Darkorange'},
    { color : 'DarkOrchid'},
    { color : 'DarkRed'},
    { color : 'DarkSalmon'},
    { color : 'DarkSeaGreen'},

    { color : 'DarkSlateGray'},
    { color : 'DarkSlateGrey'},
    { color : 'DarkTurquoise'},
    { color : 'DarkViolet'},
    { color : 'DeepPink'},

    { color : 'FireBrick'},
    { color : 'ForestGreen'},
    { color : 'Fuchsia'},
    { color : 'Gold'},
    { color : 'GoldenRod'},

    { color : 'Green'},
    { color : 'GreenYellow'},
    { color : 'HotPink'},
    { color : 'IndianRed'},
    { color : 'Indigo'},
    { color : 'Khaki'},
    { color : 'LawnGreen'},
    { color : 'LightBlue'},
    { color : 'LightPink'},
    { color : 'LightSalmon'},
    { color : 'LightSeaGreen'},

    { color : 'LightSlateGrey'},

    { color : 'Lime'},
    { color : 'LimeGreen'},

    { color : 'Magenta'},
    { color : 'Maroon'},
    { color : 'MediumAquaMarine'},
    { color : 'MediumBlue'},
    { color : 'MediumOrchid'},
    { color : 'MediumPurple'},
    { color : 'MediumSeaGreen'},

    { color : 'MediumSpringGreen'},
    { color : 'MediumTurquoise'},
    { color : 'MediumVioletRed'},

    { color : 'Navy'},
    { color : 'Olive'},
    { color : 'OliveDrab'},
    { color : 'Orange'},
    { color : 'OrangeRed'},
    { color : 'Orchid'},
    { color : 'PaleGoldenRod'},
    { color : 'PaleGreen'},
    { color : 'PaleTurquoise'},
    { color : 'PaleVioletRed'},
    { color : 'Peru'},
    { color : 'Pink'},
    { color : 'Plum'},
    { color : 'PowderBlue'},
    { color : 'Purple'},
    { color : 'Red'},
    { color : 'RosyBrown'},
    { color : 'RoyalBlue'},
    { color : 'SaddleBrown'},
    { color : 'Salmon'},
    { color : 'SandyBrown'},
    { color : 'SeaGreen'},
    { color : 'Sienna'},
    { color : 'SkyBlue'},
    { color : 'SlateBlue'},
    { color : 'SpringGreen'},
    { color : 'SteelBlue'},
    { color : 'Tan'},
    { color : 'Teal'},
    { color : 'Thistle'},
    { color : 'Tomato'},
    { color : 'Turquoise'},
    { color : 'Violet'},
    { color : 'Wheat'},

    { color : 'Yellow'},
    { color : 'YellowGreen' }
];

